### ISSUE TITLE
Image Histogram #1

### ISSUE THREAD

**Issue by IlPodd** [IlPodd/flask-classification-2022-G#1]
## Summary of the request
Create a new handle that allows picking one image from a list and returns the histogram of an image. The histogram can be rendered either in the frontend (JavaScript library, for extra points), or in the backend and passed as an image (python / matplotlib).

## Sub tasks

- [x] Copy the classification API form and modify it where it is required.
- [x] Implement the new API that takes as input the id of an image and returns the histogram.
- [x] Visualize the histogram and the image in the GUI.

## Plan for the implementation
Modify the code such that the new interface shows the dropdown menu to select the image and the submit button.
It is not required to use queues. The API can be implemented as showing the form if a GET request is issued, and the results if the POST is validated.

Modify the code such that the new interface shows the dropdown menu to select the image and the submit button.
It is not required to use queues. The API can be implemented as showing the form if a GET request is issued, and the results if the POST is validated.

**Comment by lmolinario** [comment]
I have tried to implement the requested functionality. I'm having trouble viewing the histogram. I assume these difficulties are due to the API. I reserve the right to test this theory.
Suggestions are accepted.
 thank you



![Image](https://user-images.githubusercontent.com/114803243/205313689-6b7a64c4-0c77-4153-a8c7-9acc60fe95bf.png)

**Comment by lmolinario** [comment]
I put a single startup file "start.py".   Starts the server and workers.

**Comment by lmolinario** [comment]
![Image](https://user-images.githubusercontent.com/114803243/205995586-da462833-b04d-4d16-af37-99e7286da60d.png)

**Comment by lmolinario** [comment]
![Image](https://user-images.githubusercontent.com/114803243/205996060-c5b4161c-11df-4b8f-9ee6-2d34bf40c2cd.png)




![Image](https://user-images.githubusercontent.com/114803243/205996172-a488cd3e-d73b-47b4-bb59-e0fddbe17c85.png)




![Image](https://user-images.githubusercontent.com/114803243/205996264-eebdeeef-2abb-49cb-b40b-22e0745ceb46.png)

**Comment by lmolinario** [comment]
with commit [08a04c3](https://github.com/IlPodd/flask-classification-2022-G/commit/08a04c34d8f739762d033e450e35a9a65127eeec) i solve subtask n.1 and specifically:
1. app/routes/__init__.py ->  import Histogram and histogram_id 
2. app/templates/base.html ->  insert href="/histogram">Histogram
3. config.py -> insert a QUEUE_HIST
4. requirements.txt -> add matplotlib markupsafe wtforms

**Comment by lmolinario** [comment]
with commit [baa08ce](https://github.com/IlPodd/flask-classification-2022-G/commit/baa08ce690913d4d1a7110acea3149b34b5c78c8) and [7667485](https://github.com/IlPodd/flask-classification-2022-G/commit/76674853ed12851b54669bf9606c5860748f697d)i solve subtask n. 2 and 3 and specifically:

1)	app/forms/histogram_form.py -> a create a HistogramForm(FlaskForm Class
2)	app/routes/histogram.py -> create a Flask route that handles the generation of image histograms.
3)	app/routes/histogram_id.py -> create  Flask route that retrieves the status and result of a job identified by its ID
4)	app/static/histogram.js -> create a  JavaScript function called update(jobId) and a JavaScript code block executed when the document is ready.
5)	app/templates/histogram_output.html -> extends a base template, defines a content block, and contains HTML and CSS code for displaying the image, histogram chart, loading spinner, and a "Back" button. It also includes a JavaScript file for updating the job status and rendering the histogram chart.
6)	app/templates/histogram_select.html ->  extends a base template, defines a content block, and contains HTML code for displaying a form where the user can select an image. The form is submitted using the POST method, and it includes a submit button labeled "Submit".
7)	image_histogram.py -> function fetches an image, splits it into color channels, computes the histograms for each channel, and returns a list containing the histogram data for the red, green, and blue channels of the image.
8)	worker_histogram.py -> this code sets up a worker process for histogram that connects to a Redis server, listens to a specific queue, and executes tasks from that queue. The worker continuously runs until there are no more tasks in the queue
9)	worker_histo.py -> set up a  worker for histogram
