### ISSUE TITLE
Upload Image Button #4

### ISSUE THREAD

**Issue by lmolinario** [IlPodd/flask-classification-2022-G#7]
## Summary of the request
 Add the “upload image” functionality. Implement a new route that instead of showing the dropdown list of images to select, allows the user to select an image from the computer, and returns the classification results. The button should allow the user to upload a custom image and classify it. The image should be displayed in the output interface along with the classification scores. **The old functionalities should be preserved, this is an additional feature**. Difficulty: ![image](https://user-images.githubusercontent.com/23276849/147104575-a0f77656-fb9a-421d-98e0-a2babbac77c6.png)
 
 ## Subtasks

- [x] #10
- [x]   Add the new route to the routes init file.
- [x]   Add "upload" button in the frontend (HTML).
- [x]   Implement the API for storing the image.
- [x]   Pass the image to the classification API.

 
 ## Plan for the implementation
 ![image](https://user-images.githubusercontent.com/23276849/147099172-cee8beba-6364-47de-8a7a-ba4e78dc646a.png)
 
 Implement using the Flask APIs and modifying a copy of the available classification API. No particular additional library is required.
 
 Useful links:
 
 * https://flask.palletsprojects.com/en/2.0.x/patterns/fileuploads/

**Comment by IlPodd** [comment]
Sub task 1 solved with commit [934fb26 ](https://github.com/IlPodd/flask-classification-2022-G/commit/934fb26a71740b605109caaa3669306f2fa6aa88)
(Open the commit link for details)

**Comment by IlPodd** [comment]
Sub task 2 solved with commit [d6129a3](https://github.com/IlPodd/flask-classification-2022-G/commit/d6129a3a6c3df7c952bb9e69097258eb9b4db49e) and commit [872cea9](https://github.com/IlPodd/flask-classification-2022-G/commit/872cea929e1f16898dd3c0409aaba89aeccfdef9)
(Open the commit link for details)

**Comment by IlPodd** [comment]
Sub tasks 3,4 and 5 solved with  commits [e408c7b](https://github.com/IlPodd/flask-classification-2022-G/commit/e408c7bd5759b0765bb3ad960ec1dd64789e433c) , [3c8077f](https://github.com/IlPodd/flask-classification-2022-G/commit/3c8077f6f3aeaa687b5ae64fdf51b0f682532d4b) and [e20b37b](https://github.com/IlPodd/flask-classification-2022-G/commit/e20b37bb6d000488c6c5eb9dbae79b66c48f7a41)
(Open the commit link for details)

**Comment by IlPodd** [comment]
### **Final Implementation's pictures:**

- Added the Upload button on the  index webpage  (enlightened in the image shown)

![Upload_index](https://github.com/IlPodd/flask-classification-2022-G/assets/91947876/f4bd3cde-60f0-45c4-b52c-18c8f52f0c3b)

### This is how the webpage for the image upload appears
![Upload_class_file](https://github.com/IlPodd/flask-classification-2022-G/assets/91947876/5f9a98ec-5afa-4f7e-92b8-da83b92e2856)

**Output shown after the user uploads an image**
![Upload_class_file_test](https://github.com/IlPodd/flask-classification-2022-G/assets/91947876/c3319d18-d3a8-4d32-b210-ab3f60ef033c)
